aws_region              = "us-west-2"
vpc_cidr_block          = "10.0.0.0/16"
public_subnet_cidr_block = "10.0.1.0/24"
public_subnet_az        = "us-west-2a"
ami_id                  = "ami-12345678"
instance_type           = "t2.micro"
route53_zone_name       = "example.com"
